### PR TITLE
refactor: replace -h with value provided by MemoryMXBean

### PR DESCRIPTION
**Pull request by kcpeppe**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by earthling-amzn** [comment]
Hello! Thank you for this contribution. 

The change to detect compressed oops configuration looks good. However, I believe the intent with heap size (-h) was that it represent the _maximum_ heap size (see [description of constructor parameter](https://github.com/corretto/heapothesys/blob/master/HyperAlloc/src/main/java/com/amazon/corretto/benchmark/hyperalloc/SimpleRunConfig.java#L86)). For this reason, I believe we want `MemoryUsage::getMax` instead of `MemoryUsage::getCommitted`. 

This change will also break the tests: `SimpleRunConfigTest::DefaultStringsTest` and `SimpleRunConfigTest::StringArgsTest`. I think it's fine to just remove the failing assertion, since the benchmark will no longer accept the `-h` parameter. I realize now that the recent removal of the security manager also breaks a couple of tests. I will fix these separately and will not hold you accountable for them. :sweat_smile:

**Review by earthling-amzn — CHANGES_REQUESTED** [review]
Please fix related tests in SimpleRunConfigTest.

**Comment by kcpeppe** [comment]
I'll take a look at the security manager issues at the same time as fixing the max heap issue.

**Comment by kcpeppe** [comment]
all of the tests aside from the security manager should be functional now.

**Review by earthling-amzn — APPROVED** [review]
Thank you for fixing the tests and this contribution!

**Pull request merged**
